# Generated by Django 6.0.1 on 2026-02-01 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_created_at_job_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
