# Generated by Django 6.0.1 on 2026-02-01 00:49

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_vacancy_alter_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=1, validators=[job.models.validate_not_niegative]),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1, validators=[job.models.validate_not_niegative]),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[job.models.validate_salary]),
        ),
    ]
